services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /home/juanchobanano/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=America/Bogota
    network_mode: host
    privileged: true
    restart: unless-stopped

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0
    network_mode: host
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  code-server:
    container_name: code-server
    image: linuxserver/code-server
    volumes:
      - /home/juanchobanano/homeassistant:/config
    ports:
      - "8443:8443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    restart: unless-stopped

  n8n:
    container_name: n8n
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"   # Puerto donde n8n estar치 accesible
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true        # Activar autenticaci칩n b치sica
      - N8N_BASIC_AUTH_USER=admin        # Usuario para login
      - N8N_BASIC_AUTH_PASSWORD=supersecretpassword  # Contrase침a para login
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_HOST=0.0.0.0
    volumes:
      - ./n8n:/home/node/.n8n   # Persistencia de datos de n8n
